update configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,14 +1,20 @@
 #!/bin/sh
-# This is free and unencumbered software released into the public domain.
-# For more information, please refer to <http://unlicense.org/>
+# Public Domain
 #
+
+WCURDIR=$(pwd)
+export WCONF_SCRIPTDIR=$(cd "$(dirname "$0")" ; pwd -P)
+export WCONF_CONFIGURE=${WCONF_SCRIPTDIR}/$(basename "$0")
+
+if [ "$WCURDIR" != "$WCONF_SCRIPTDIR" ] ; then
+    echo "Current dir: $WCURDIR"
+    echo "Wconf dir  : $WCONF_SCRIPTDIR"
+    echo "Out-of-tree builds are not supported..."
+    exit 1
+fi
 
 if ! [ -f Makefile ] ; then
 	echo 'Main Makefile is missing, cannot continue'
-	exit 1
-fi
-
-if ! cd $(dirname "$0") ; then
 	exit 1
 fi
 
@@ -23,6 +29,7 @@ config_mk_flags=
 w_files_in=
 sysroot=
 
+#==========================================================
 
 w_new_option() # $1=opt [$2=env_variable]
 {
@@ -39,9 +46,35 @@ w_new_option_with()
 	w_opts_check="$w_opts_check $1"
 }
 
+exit_error() {
+	test "$1" && echo "$@"
+	if [ -f config.log ] ; then
+		echo "See config.log, there might be some clues there"
+	fi
+	rm -f config.h config.mk
+	exit 1
+}
 
-if [ -f configure.project ] ; then
-	. ./configure.project
+cmdecho()
+{
+    echo "# $@"
+    "$@"
+}
+
+getvalue()
+{
+	echo $1 | cut -f 2 -d '='
+}
+
+include()
+{
+    . ${WCONF_SCRIPTDIR}/w_conf/${1} || exit 1
+}
+
+#==========================================================
+
+if [ -f ${WCONF_SCRIPTDIR}/configure.project ] ; then
+	. ${WCONF_SCRIPTDIR}/configure.project
 fi
 
 if [ -z "$PROJECT_TYPE" ] ; then
@@ -59,35 +92,29 @@ PACKAGE_VERSION="${VERSION}"
 #==========================================================
 # ./configure release [xz|gz|lz|bz2|zst]
 
-if [ "$1" = "release" ] ; then
-	srcdir=$(pwd)
+if [ "$1" = "release" ] || [ "$1" = "dist" ] ; then
+	srcdir=${WCONF_SCRIPTDIR}
 	outdir=${PACKAGE}-${VERSION}
-	cd ..
-	rm -rf ${outdir}
-	if [ "$2" = "dist" ] ; then
-		# force creation of tarfile, copy the whole dir
-		shift
-		shift
-		cp -rf ${srcdir} ${outdir}
-		cd ${outdir}
-		git clean -dfx
-		rm -rf .*
-		cd ..
-	else
-		if command -v git >/dev/null; then
-			printf "Run 'git clean -dfx'? [y/N]: "
-			read anzwer
-			case $anzwer in y|Y)
-				cd ${srcdir}
-				echo '# git clean -dfx'
-				git clean -dfx
-				cd ..
-				;;
-			esac
-		fi
-		mkdir -p ${outdir}
-		cp -rf ${srcdir}/* ${outdir}/
+	if [ ! -d .git ] ; then
+		echo "Warning: no .git directory, will not be able to perform 'git clean'"
 	fi
+	if [ ! -d .git ] ; then
+		echo "Warning: no .gitignore file, it contains rules to delete unwanted files, the release tarball may not be suitable for release"
+	fi
+	if [ "$outdir" = "$(basename $srcdir)" ] ; then
+		echo "ERROR: output dir ($outdir) is the also input directory"
+		exit 1
+	fi
+	cmdecho cd ..
+	cmdecho rm -rf ${outdir}
+	cmdecho cp -rf ${srcdir} ${outdir}
+	cmdecho mkdir -p ${outdir}
+	cmdecho cd ${outdir}
+	if command -v git >/dev/null; then
+		cmdecho git clean -dfx
+	fi
+	rm -rf .[a-z]* .[A-Z]* .[0-9]*
+	cmdecho cd ..
 	#--
 	echo "# tar -vcf ${outdir}.tar ${outdir}"
 	tar -vcf ${outdir}.tar ${outdir}
@@ -103,27 +130,17 @@ if [ "$1" = "release" ] ; then
 		*)   cmd=${comp} ;;
 	esac
 	rm -f ${outdir}.tar.${comp}
-	echo "# ${cmd} ${outdir}.tar"
-	if ${cmd} ${outdir}.tar ; then
+	if cmdecho ${cmd} ${outdir}.tar ; then
 		echo "*** ${outdir}.tar.${comp} has been created..."
+		exit 0
 	fi
 	rm -f ${outdir}.tar
-	exit
+	exit 1
 fi
 
 # w_conf/gettext: ./configure po|pot
 
 #==========================================================
-
-exit_error() {
-	test "$1" && echo "$@"
-	if [ -f config.log ] ; then
-		echo "See config.log, there might be some clues there"
-	fi
-	rm -f config.h config.mk
-	exit 1
-}
-
 
 check_command() # 1:<cmd> finds $1 in $PATH
 {
@@ -166,14 +183,9 @@ set_cc()
 		CC_IS_FULL_PATH=1 ;;
 	esac
 	GCC="no"
-	if [ -n "$CC" ] ; then
-		zz_list="$CC"
-	else
-		zz_list="cc gcc clang"
-	fi
 	printf "Checking for C compiler... "
-	ZCC="$(check_command ${zz_list})"
-	if test -z "$ZCC" ; then
+	ZCC="$(check_command ${CC:-cc gcc clang})"
+	if [ -z "$ZCC" ] ; then
 		exit_error "$CC not found"
 	fi
 	CC="$ZCC"
@@ -196,18 +208,9 @@ set_cxx()
 	esac
 	#--
 	printf "Checking for C++ compiler... "
-	if [ -n "$CXX" ] ; then
-		zz_list="$CXX"
-	else
-		zz_list="c++ g++ clang++"
-	fi
-	ZXX="$(check_command ${zz_list})"
-	if test -z "$ZXX" ; then
-		if [ -z "$CXX" ] ; then
-			echo "not found" # not a fatal error
-		else
-			exit_error "$CXX not found"
-		fi
+	ZXX="$(check_command ${CXX:-c++ g++ clang++})"
+	if [ -z "$ZXX" ] ; then
+		exit_error "$CXX not found"
 	fi
 	CXX="$ZXX"
 	echo "$CXX"
@@ -220,40 +223,28 @@ set_cxx()
 set_w_pkg_config()
 {
 	printf "Checking for pkg-config... "
-	W_PKG_CONFIG=''
-	if [ -n "${PKG_CONFIG}" ] ; then
-		W_PKG_CONFIG="$(check_command ${PKG_CONFIG})"
-		if [ -n "$W_PKG_CONFIG" ] ; then
-			echo "$W_PKG_CONFIG (environment)"
-			return 0
-		fi
+	W_PKG_CONFIG="$PKG_CONFIG"
+	if [ -z "${W_PKG_CONFIG}" ] ; then
+		W_PKG_CONFIG="$(check_command pkg-config pkgconf)"
 	fi
-	W_PKG_CONFIG="$(check_command pkg-config pkgconf)"
-	if [ -n "$W_PKG_CONFIG" ] ; then
-		echo "$W_PKG_CONFIG [$($W_PKG_CONFIG --version 2>/dev/null)]"
-	else
+	if [ -z "${W_PKG_CONFIG}" ] ; then
 		echo "no"
-		echo "WARNING: missing pkg-config: this a potentially fatal error"
+		return
+	fi
+	echo "$W_PKG_CONFIG [$($W_PKG_CONFIG --version 2>/dev/null)]"
+	if [ -n "$static_link" ] ; then #force static
+		case ${W_PKG_CONFIG} in
+			*--static*) ok=1 ;;
+			*) W_PKG_CONFIG="$W_PKG_CONFIG --static" ;;
+		esac
 	fi
 }
 
-
-run_pkg_config()
-{
-	if [ -n "$static_link" ] ; then
-		pkgconfig_s='--static'
-	else
-		pkgconfig_s=''
-	fi
-	if test -n "$W_PKG_CONFIG" ; then
-		${W_PKG_CONFIG} ${pkgconfig_s} "$@"
-	else
-		pkg-config ${pkgconfig_s} "$@"
-	fi
+run_pkg_config() {
+	${W_PKG_CONFIG:-pkg-config} "$@"
 }
 
-w_pkgconfig_run()
-{
+w_pkgconfig_run() {
 	run_pkg_config "$@"
 }
 
@@ -270,30 +261,33 @@ w_pkgconfig_check() # $1=<pkg> $2=[min-version]
 	fi
 	if [ -z "$W_PKG_CONFIG" ] ; then
 		echo "no (!!pkg-config is missing!!)"
-		return 1
+		return 1  #error
 	fi
 	#--
-	if [ -n "$pc_pkg_min_ver" ] ; then
-		run_pkg_config ${pc_pkg} --exists --atleast-version=${pc_pkg_min_ver}
-	else
-		run_pkg_config ${pc_pkg} --exists
+	run_pkg_config ${pc_pkg} --exists
+	if [ $? -ne 0 ] ; then
+		echo "no"
+		return 1  #error
 	fi
-	xret=$?
-	if [ $xret -eq 0 ] ; then
-		echo "yes [$(run_pkg_config ${pc_pkg} --modversion)]"
-	else
-		if [ -n "$pc_pkg_min_ver" ] ; then
-			xxzzfound=$(run_pkg_config ${pc_pkg} --modversion 2>/dev/null)
-			if [ -n "$xxzzfound" ] ; then
-				echo "no [found $xxzzfound]"
+	xpkgverx="$(run_pkg_config ${pc_pkg} --modversion 2>/dev/null)"
+	if [ -n "$pc_pkg_min_ver" ] ; then
+		run_pkg_config ${pc_pkg} --atleast-version=${pc_pkg_min_ver}
+		if [ $? -ne 0 ] ; then
+			if [ -n "$xpkgverx" ] ; then
+				echo "no [found $xpkgverx]"
+				return 1  #error
 			else
 				echo "no"
+				return 1  #error
 			fi
-		else
-			echo "no"
 		fi
 	fi
-	return $xret
+	if [ -n "$xpkgverx" ] ; then
+		echo "yes [${xpkgverx}]"
+	else
+		echo "yes"
+	fi
+	return 0  #ok
 }
 
 
@@ -308,7 +302,7 @@ w_compile_c_code() # $1:code  $2:extra-CFLAGS  $3:extra-LDFLAGS
 	echo "$CC $CFLAGS $2 ${conftest}.c -o ${conftest}.o $LDFLAGS $3" >>config.log
 	$CC $CFLAGS $2 ${conftest}.c -o ${conftest}.o $LDFLAGS $3 2>>config.log
 	zzzzretxx=$?
-	rm -f ${conftest}.c ${conftest}.o
+	rm -f ${conftest}.c ${conftest}.o ${conftest}.exe
 	return ${zzzzretxx}
 }
 
@@ -467,8 +461,8 @@ w_require_gnu_make()
 
 #==========================================================
 
-#test "$CC"    || CC='gcc'
-#test "$CXX"   || CXX='g++'
+#test "$CC"    || CC='cc'
+#test "$CXX"   || CXX='c++'
 test "$STRIP"  || STRIP='strip'
 test "$AR"     || AR='ar'
 test "$AS"     || AS='as'
@@ -476,7 +470,6 @@ test "$NM"     || NM='nm'
 test "$RANLIB" || RANLIB='ranlib'
 test "$OBJCOPY" || OBJCOPY='objcopy'
 test "$OBJDUMP" || OBJDUMP='objdump'
-static_link=''
 # mingw
 test "$DLLTOOL" || DLLTOOL='dlltool'
 test "$WINDRES" || WINDRES='windres'
@@ -498,10 +491,15 @@ infodir='${datarootdir}/info'
 mandir='${datarootdir}/man'
 localedir='${datarootdir}/locale'
 runstatedir='${localstatedir}/run'
-top_builddir="$(pwd)"
-top_srcdir="$(pwd)"
+top_builddir="${WCONF_SCRIPTDIR}"
+top_srcdir="${WCONF_SCRIPTDIR}"
 builddir=.
 srcdir=.
+
+## env vars should not change some important variables
+host=
+build=
+static_link=''
 
 print_eval_var()
 {
@@ -617,14 +615,11 @@ print_extra_env_variables()
 
 #==========================================================
 
-getvalue() {
-	echo $1 | cut -f 2 -d '='
-}
-
 for i in $@
 do
 	case $i in
-		--host=*) host="$(getvalue $i)" ;;
+		--build=*) build="$(getvalue $i)" ;;
+		--host=*)  host="$(getvalue $i)"  ;;
 		CFLAGS=*)   CFLAGS="$CFLAGS $(getvalue $i)"     ;;
 		CPPFLAGS=*) CPPFLAGS="$CPPFLAGS $(getvalue $i)" ;;
 		LDFLAGS=*)  LDFLAGS="$LDFLAGS $(getvalue $i)"   ;;
@@ -668,10 +663,6 @@ do
 	esac
 done
 
-if [ -n "$W_PKG_CONFIG_STATIC" ] ; then
-	static_link=1
-fi
-
 for confx in ${w_opts_configure} ${extra_configure_opts} ${extra_packages_opts}
 do
 	opt_configure_${confx} "$@"
@@ -688,7 +679,19 @@ OS_BUILD=$(uname -s)
 OS_CROSS=''
 OS_TARGET=''
 
-if test -n "$host" ; then
+MACHINE_CC=$($CC -dumpmachine 2>/dev/null)
+
+if [ -z "$build" ] ; then
+	build=${MACHINE_CC}
+fi
+
+if [ -n "$host" ] ; then
+	if [ "$host" = "$build" ] ; then
+		host=
+	fi
+fi
+
+if [ -n "$host" ] ; then
 	printf "Checking cross-compiler... "
 	CROSS_IS_FULL_PATH=''
 	CROSS_BASE_DIR=''
@@ -774,43 +777,44 @@ fi
 
 #==========================================================
 
+EXE=''
 case ${OS_BUILD} in
-	CYGWIN*) OS_BUILD="Cygwin" ;;
-	MINGW*)  OS_BUILD="MinGW"  ;;
-	MSYS*)   OS_BUILD="MinGW"  ;;
+	CYGWIN*) OS_BUILD="Cygwin" ; EXE = '.exe' ;;
+	MINGW*|MSYS*)  OS_BUILD="MinGW" ; EXE = '.exe' ;;
+	UWIN*|Windows*)OS_BUILD="MinGW" ; EXE = '.exe' ;;
+	MS-DOS*) OS_BUILD="MSDOS" ; EXE = '.exe' ;;
 esac
 
 OS_TARGET=${OS_BUILD}
 
 if [ -n "$OS_CROSS" ] ; then
 	# cross-compiling, reset OS_TARGET
+	EXE=''
 	OS_TARGET=''
 	# determine OS_TARGET again
 	case $OS_CROSS in
-		*-mingw*)   OS_TARGET='MinGW'   ;;
+		*-mingw*)   OS_TARGET='MinGW' ; EXE='.exe' ;;
 		*-darwin*)  OS_TARGET='Darwin'  ;;
 		*-linux-*)  OS_TARGET='Linux'   ;;
 		*-freebsd*) OS_TARGET='FreeBSD' ;;
+		*-openbsd*) OS_TARGET='OpenBSD' ;;
+		*-netbsd*)  OS_TARGET='NetBSD'  ;;
+		*-haiku*)   OS_TARGET='Haiku'   ;;
+		*-msdos*)   OS_TARGET='MSDOS' ; EXE='.exe' ;;
 	esac
 fi
-
-case $OS_TARGET in
-	Linux)   SYSDEFINE='__linux__=1' ;;
-	MinGW)   SYSDEFINE='__MINGW32__=1' ;;
-	FreeBSD) SYSDEFINE='__FreeBSD__=1' ;;
-	Darwub)  SYSDEFINE='__APPLE__=1' ;;
-esac
 
 TARGET_OS="$OS_TARGET"
 
 #==========================================================
+# PROJECT_FLAGS go first (can be overridden)
 
-CFLAGS="$CFLAGS $PROJECT_CFLAGS"
-CPPFLAGS="$CPPFLAGS $PROJECT_CPPFLAGS"
-CXXFLAGS="$CXXFLAGS $PROJECT_CXXFLAGS"
-LDFLAGS="$LDFLAGS $PROJECT_LDFLAGS"
-LXXFLAGS="$LXXFLAGS $PROJECT_LXXFLAGS"
-LIBS="$LIBS $PROJECT_LIBS"
+CFLAGS="$PROJECT_CFLAGS $CFLAGS"
+CPPFLAGS="$PROJECT_CPPFLAGS $CPPFLAGS"
+CXXFLAGS="$PROJECT_CXXFLAGS $CXXFLAGS"
+LDFLAGS="$PROJECT_LDFLAGS $LDFLAGS"
+LXXFLAGS="$PROJECT_LXXFLAGS $LXXFLAGS"
+LIBS="$PROJECT_LIBS $LIBS"
 
 #==========================================================
 
@@ -844,13 +848,27 @@ done
 #                  config.mk
 #==========================================================
 
+w_aftercheck_func
+
 # ensure -DHAVE_CONFIG_H
 CFLAGS="-DHAVE_CONFIG_H $CFLAGS "
 CXXFLAGS="-DHAVE_CONFIG_H $CXXFLAGS"
 
+# some variables might contain stuff to be evaluated
+if [ -n "$MK_SUBDIRS" ] ; then
+	MK_SUBDIRS="$(eval echo $MK_SUBDIRS)"
+fi
+if [ -n "$MK_DISTCLEAN_FILES" ] ; then
+	MK_DISTCLEAN_FILES="$(eval echo $MK_DISTCLEAN_FILES)"
+fi
+
 cat > config.mk <<EOF
 # generated by ./configure
 ${W_GNU_MAKE}
+
+SUBDIRS = ${MK_SUBDIRS}
+DISTCLEAN_FILES = ${MK_DISTCLEAN_FILES}
+MK_CHECK = ${MK_CHECK}
 
 prefix = ${prefix}
 exec_prefix = ${exec_prefix}
@@ -906,7 +924,8 @@ OBJDUMP = ${OBJDUMP}
 
 DLLTOOL = ${DLLTOOL}
 WINDRES = ${WINDRES}
-WINDMC = ${WINDMC}
+WINDMC  = ${WINDMC}
+EXE     = ${EXE}
 
 CFLAGS = ${CFLAGS}
 CPPFLAGS = ${CPPFLAGS}
@@ -917,7 +936,6 @@ LIBS = ${LIBS}
 
 #=================================================
 
-${SYSDEFINE}
 ${make_extra_flags}
 ${w_config_mk_extra_lines}
 EOF
@@ -984,6 +1002,7 @@ OBJDUMP="${OBJDUMP}"
 DLLTOOL="${DLLTOOL}"
 WINDRES="${WINDRES}"
 WINDMC="${WINDMC}"
+EXE="${EXE}"
 
 CFLAGS="${CFLAGS}"
 CPPFLAGS="${CPPFLAGS}"
@@ -994,7 +1013,6 @@ LIBS="${LIBS}"
 
 #=================================================
 
-${SYSDEFINE}
 ${config_sh_extra}
 EOF
 
@@ -1006,7 +1024,7 @@ ${env}_LIBS  = $(eval echo \$${env}_LIBS)" >> config.mk
 		#--
 		echo "${env}_CFLAGS=\"$(eval echo \$${env}_CFLAGS)\"
 ${env}_LIBS=\"$(eval echo \$${env}_LIBS)\"" >> config.sh
-    done
+	done
 fi
 
 
@@ -1024,7 +1042,7 @@ fi
 
 #==========================================================
 
-. ./config.sh
+. ${WCONF_SCRIPTDIR}/config.sh
 
 #==========================================================
 #                       config.h
@@ -1079,7 +1097,7 @@ fi
 
 for infile in ${w_infiles}
 do
-	./w_conf/00_standard_infile.sh ${infile}
+	${WCONF_SCRIPTDIR}/w_conf/00_standard_infile.sh ${infile}
 done
 
 #==========================================================
